local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.2
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 0.5
  height: 0.5
  resolution: 0.05
  transform_tolerance: 1
